version: '3.3'

services:
  laravel_api-login:
    image: docker.io/bitnami/laravel:10
    ports:
      - '8081:8000'
    environment:
      - DB_HOST=185.60.40.210
      - DB_PORT=3306
      - DB_USERNAME=Iker
      - DB_PASSWORD=12345678
      - DB_DATABASE=Iker
    volumes:
      - './contenedores/laravel_api-login:/app'

  apache:
    image: httpd:latest
    volumes:
      - ./contenedores/pagina_web/:/usr/local/apache2/htdocs/
    ports:
      - "8082:80"

  laravel_api-bbdd:
    image: docker.io/bitnami/laravel:10
    ports:
      - '8083:8000'
    environment:
      - DB_HOST=185.60.40.210
      - DB_PORT=3306
      - DB_USERNAME=Iker
      - DB_PASSWORD=12345678
      - DB_DATABASE=Iker
    volumes:
      - './contenedores/laravel_api-bbdd:/app'
    command: ["php", "artisan", "schedule:work"]


  nginx:
    image: nginx:latest
    volumes:
      - ./contenedores/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8084:80"
