version: '3.3'

services:
  laravel_api-login:
    image: markosmartinez/laravelpassport-php8.2
    ports:
      - '8081:8000'
    volumes:
      - './contenedores/laravel_api-login/:/var/www/html/'

  apache:
    image: httpd:latest
    volumes:
      - ./contenedores/pagina_web/:/usr/local/apache2/htdocs/
    ports:
      - "8082:80"

  laravel_api-bbdd:
    image: markosmartinez/laravelpassport-php8.2
    ports:
      - '8083:8000'
    environment:
      USAR_WORKER: 1
      
       
    volumes:
      - './contenedores/laravel_api-bbdd/:/var/www/html/'


  nginx:
    image: nginx:latest
    volumes:
      - ./contenedores/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8084:80"


  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'ProyectoFinal'
      MYSQL_USER: 'Iker'
      MYSQL_PASSWORD: '1234'
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./datosProyecto/mysql/:/var/lib/mysql

  phpmyadmin:
        image: 'phpmyadmin:latest'
        ports:
            - 8085:80
        environment:
            - PMA_ARBITRARY=1    
