version: '3.3'

services:
  apache: #servidor de apache n.1
          image: httpd:latest #imagen del contenedor
          volumes:
          - ./Proyecto/pagina_web/:/usr/local/apache2/htdocs/ #a que documento hace referencia
          ports: #puertos
          - "8082:80"
           
  nginx:
         image: nginx:latest
         volumes: 
         - ./datos_reto/nginx.conf:/etc/nginx/nginx.conf #archivo de configuracion para este servidor
         ports:
         - "8080:80"

  laravel_api-bbdd:
      image: docker.io/bitnami/laravel:10
      ports:
        - '8081:8000'
      environment:
        - DB_HOST=185.60.40.210
        - DB_PORT=3306
        - DB_USERNAME=Iker
        - DB_PASSWORD=12345678
        - DB_DATABASE=Iker
      volumes:
        - './datos_reto/laravel_api-bbdd:/app'